{% set name = "momepy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cb3473862e2f0dc3a8ab8f032eddfe2b5ca2d840f6b0b92374c00787f0fdb85

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - geopandas
    - networkx
    - libpysal
    - tqdm
    - gdal >=2.4

test:
  imports:
    - momepy

about:
  home: http://momepy.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Urban Morphology Measuring Toolkit for Python

  description: |
    Momepy is a project allowing advanced quantitative analysis of urban morphology.
    Embracing principles of Urban Morphometrics, this toolkit aims to provide tools
    for the development of complex frameworks for a description of urban structures.
  doc_url: http://docs.momepy.org
  dev_url: https://github.com/martinfleis/momepy

extra:
  recipe-maintainers:
    - martinfleis
