{% set name = "momepy" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d4f8c544c076f7117e911e3fa47bdad92c0f6e887338f9d8abbc491129aaa5f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - geopandas >=0.8
    - networkx
    - libpysal
    - tqdm
    - pygeos
    - scipy

test:
  imports:
    - momepy

about:
  home: http://momepy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Urban Morphology Measuring Toolkit for Python

  description: |
    Momepy is a project allowing advanced quantitative analysis of urban morphology.
    Embracing principles of Urban Morphometrics, this toolkit aims to provide tools
    for the development of complex frameworks for a description of urban structures.
  doc_url: http://docs.momepy.org
  dev_url: https://github.com/martinfleis/momepy

extra:
  recipe-maintainers:
    - martinfleis
    - jGaboardi
